### ISSUE TITLE
Add a page listing options for installing user scripts

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#10]
Greasemonkey, Scriptish, etc.

**Comment by esperecyan** [comment]
Opera 12.x is no longer maintained since Opera 12.16 was released on July 4, 2013.
https://twitter.com/saito/status/374575809555484672
"Opera 16 became Stable after Opera 15, and I think they could be considered maintenance releases of Presto version are no longer provided including about security."

Opera 12.17 was released on April 23, 2014, but it is only for autoupdater and I think using Opera 12.x remains dangerous.
