### ISSUE TITLE
Make Antifeatures Less Prominent

### ISSUE THREAD

**Issue by FlareZ123** [JasonBarnabe/greasyfork#1049]
(I am a large GreasyFork script maker and I've been watching the effects of the new antifeature tag - not good)
I think antifeatures have to be toned down in terms of their prominence on this site, since they are leading to massive blatant false reviews and spam, for example: <a href="https://greasyfork.org/en/scripts/374794-moomoo-io-krunker-mope-allsites-more-super-mod-insta-all-upgrades-autoheal-pro-cursor-100-res/feedback">here</a> (500K+ downloads, 500+ daily downloads, but constant bad reviews)
Just because a script has antifeatures, people seem to believe it is malware - not to mention constant emails of reports that are just "malware" or "spam" with absolutely nothing to back up their claims.  Not to mention the excessive wordiness of GreasyFork's warning towards antifeature scripts:
> Before you install, Greasy Fork would like you to know that this script contains antifeatures, which are things there for the script author's benefit, rather than yours.

"antifeatures" exist in almost every single piece of software today, and it is handled by other companies, organizations, etc. with privacy policies and simplicity (without interfering with user downloads, unlike this).
For example, the Chrome web store informs the users of privacy notices on an entirely different section of an extension download, and Chrome considers these extensions high level privileged code, so much so that they review scripts (similar to what GreasyFork does with updates)
I was going to comment on the original antifeatures thread, but I never expected GreasyFork to actually apply such a harsh and invasive anti-antifeatures stance, so this is why I'm making this issue.

To make it succinct:
-prominent antifeatures lead to bad reviews and malware out of the script authors' control,
-more popups and so much wording in antifeature warnings make it seem like malware and it makes users think twice about downloading scripts; maybe this is intended but users already accept to so much without caring (but at least userscripts are open source and antifeatures can be shown in the data block) and this is just interfering with actual script authors on GreasyFork
-antifeatures could just be disclosed in the data block of the script WITHOUT interfering with user experience by making an extremely annoying wordy popup, while keeping transparency.

**Comment by DaTigerYT** [comment]
I have to agree with Flare here, the anti-feature meta tag is a great addition but its current implementation needs improvements.

<h2>My concerns</h2>

<h3>The installation warning message is too vague/untrue</h3>

Here's an example of the warning message for a script including tracking:
> This script contains antifeatures
> 
> Before you install, Greasy Fork would like you to know that this script contains antifeatures, which are things there for the script author's benefit, rather than yours.
> 
> This script contains code that will track your browsing.

What makes this so bad is the fact it lacks context and the words "for the script author's benefit, rather than yours" imply malicious content. But that's simply may not be true depending on the content.

According to the [anti-feature rules](https://greasyfork.org/en/help/antifeatures), any script that includes code that tracks "user activity" must include the "tracking" anti-feature tag.

What this means, is if I had a script that records what a user tends to click on from a certain store after a search and then sorts all items on that store to what the user is most likely to view. That would mean I'd have to add the tracking anti-feature. However, my hypothetical script's sole purpose is to make the shopping process on the store much easier for the user, eliminating the process of searching and the script author doesn't benefit from it at all.

But, since people wanting the script will see "for the script author's benefit, rather than yours" they will not install the script and in return not get the benefits of the scripts they could've had.

<i>Without much research, [this](https://sleazyfork.org/en/scripts/394998-e-hentai-base-history-recommand-gallerys) script seems to do a similar function to my hypothetical script.</i>

And here's another warning message for "ads":
> This script will inject ads on the sites you visit.

"Will"? What if my script has a toggleable switch, disabled by default that if turned on, will enable ads? I guess, it's technically a donation as the user willingly toggled the switch on to enable ads but the main thing here is, the script "will" not inject ads on the sites the user visits. Only when the user wants the script to inject the ads.

And also, "the sites"? What if the script has only matched with one site and will one that specific one? I mean sure I guess your script is titled "Amazon.com Script" people can make assumptions but we all know people are stupid, they won't look at the code / can't read it and will question whether the script will continue to inject ads off amazon.com or maybe when the script isn't even enabled.

<h3>The anti-feature rules are too strict</h3>

I'll make this one short. As quoted from the rules:

> The script requires the user to pay the script author for the script to be fully functional.
> 
> The following do not require the use of @antifeature payment:
> 
> A script that affects a website that requires payment, but the script itself does not require payment.
> A script that asks for donations, as long as the donation does not unlock additional functionality.

What if my script has a single, very specific feature out of a library of free features, that the user has to pay for. 
![image](https://user-images.githubusercontent.com/35151380/159186615-d65f7caa-02e9-4c29-96ca-793b740020ce.png)
Imagine a script has all these features ^^ and then there's 1 feature where if a user spends 10p (Yes, I'm British), the background of the site turns blue. And just because of that tiny feature, the entire script needs an antifeature payment warning that states "This script is only fully functional after you make a payment."... The statement is technically true but it suggests half of the features, perhaps even more are blocked behind a paywall.

<h2>Proposed solutions</h2>

Honestly, the solutions are quite simple: make the phrasing of the rules and warning messages clearer and provide explanations for each anti-feature, upon installing the script.

The quite pessimistic (negative, regardless of whether the use-case could be positive):
> Before you install, Greasy Fork would like you to know that this script contains antifeatures, which are things there for the script author's benefit, rather than yours.

Could be changed to:
> Before you install, Greasy Fork would like to warn you that this script contains anti-features which <b>if used incorrectly may</b> benefit script author, rather than you.

The impulsive (jumping to conclusions):
> This script will inject ads on the sites you visit.

Could be changed to:
> When enabled, this script may inject ads into the sites the script will be applied to.
> When enabled, this script may inject ads into google.com, gmail.com, youtube.com.

And the vague:
> This script contains code that will track your browsing.

Could be changed to:
... This is getting long, I hope I've made my point clear.

<hr>

I mean come on, the warning message for "miner" is:
> This script contains a crypto-miner that will use your device's resources when active.

Without context, that just sounds like the script is a virus or malware.

**Comment by JasonBarnabe** [comment]
Users **must** be informed of anti-features before they install. The current system does that with text on the page and a warning pop-up. If it somehow wasn't possible to tell users, then Greasy Fork would revert back to making anti-features explicitly against the rules.

Script authors have a chance to explain exactly what the anti-feature entails. This text is displayed on the pop-up. I'm open to making changes to Greasy Fork's text, but I don't agree with any of the suggestions by @DaTigerYT, which seem to mostly be adding hedging words. If an author has added `@antifeature ads` or `@antifeature tracking`, then that script **does** inject ads or **does** do tracking. Not _may_, not _if used incorrectly_. It definitely does do those things.

Script authors can include an explanation of the anti-feature so they can say "I only add ads on example.com" or "I only track you when you do X". This explanation will show in the pop-up, so you can provide all the context you like.

If a script is reported for an anti-feature it already disclosed, then that's an easy report for moderators to dismiss. The script is unaffected by such reports.

If a script receives a bad review for an anti-feature that is disclosed, well that's their opinion and a valid review. Same situation as if Google Chrome started tracking everything you did, it would totally valid for you to blast them about it in a review.

**Comment by FlareZ123** [comment]
> The current system does that with text on the page and a warning pop-up.

This is the issue I'm getting at, the current system is too alarmist for users and script authors.
For script authors: when a user sees "this script tracks your browsing", this has already psychologically marked it in their brains as malware, especially in the userscript community where people blindly download code that they may or may not understand. Even just the phrasing "antifeature" has a negative connotation.

The decision of a user to download a script or not is not only based on whether they think it is good (in terms of antifeatures and actual features), it is their reaction to *GreasyFork's* words, not script authors' use, because GF's words will be read before our justifications are read, and a user's mind will already be made up for or against our products: malware or just regular software.
The above means that this:
> Script authors can include an explanation of the anti-feature so they can say "I only add ads on example.com" or "I only track you when you do X". This explanation will show in the pop-up, so you can provide all the context you like.

Is irrelevant, because users already made up their minds because of GreasyFork's overly alarmist phrases in warning.

So, I believe the ideal solution is to remove GreasyFork's popup and hoist the "Antifeatures | Tracking" meta tag to be above the "Author | <name>" meta tag, so it is the first thing they read **without intruding their experience**. More popup boxes also create a psychological resistance to antifeatures and a warning becomes useless as a warning, for example, [Proposition 65](https://oehha.ca.gov/proposition-65) created the effect of consumers not caring about "chemicals known to the state [that] cause cancer or reproductive toxicity." This is exactly the effect that GreasyFork has made: it has used alarmist and misleading phrases (as Tiger described above), combined with an accidental creation of a psychological tolerance buildup to those warning signs.

However, the largest scripts are affected by the psychological tolerance to the antifeature warning because they will most likely be what the users download first, and that will be where they either download or not download antifeature-inclusive scripts *first*.

To restate, there are two solutions:
-let script authors create the popup warning box without GF's words (can be checked by moderators)
-remove the popup warning altogether and add emphasis on the antifeature meta tag (and include the justification somewhere there, likely in another meta tag)

**Comment by Illya9999** [comment]
I think a good solution to this might be instead of using a popup but instead having a banner on the page that discloses the antifeatures. This would allow users to easily see what potential red flags the script could have without making downloading of the scripts harder.

**Comment by ABCxFF** [comment]
FlareZ, I agree completely. As a web developer, and a greasyfork user I also believe the prominence of the anti-features are having a negative affect on user experience, specifically the script developer's experience.

I personally think there should just be a way to link to a privacy policy of some sort, whether within the script's description or maybe external, so that a script user can easily access the information necessary to judge the script they're installing. This might not be necessary though - all I am sure of is that the anti-features need to be changed.

**Comment by JasonBarnabe** [comment]
I'm still of the opinion that it should not be made less prominent. It should be front-and-center when the user wants to install the script. I am still open to adjusting the wording or the situations that require the use of `@antifeature`, but I haven't heard any suggestions that I've liked in this issue.
