### ISSUE TITLE
[Feature Request] Retain search parameters when clicking **More..** in the sites sidepanel

### ISSUE THREAD

**Issue by TFWol** [JasonBarnabe/greasyfork#1137]
They're retained when clicking on an entry in the side panel, but lost once you click the **More...** button and choose a site from the list.

# Example
1. You search for `this is a test` and sort by **Updated date**
2. Hover over site listing at the right sidebar, like **youtube.com** and you'll see `https://greasyfork.org/en/scripts/by-site/youtube.com?q=this+is+a+test&sort=updated` which, when clicked, will retain your query and sort.
3. Hover over **More...** and you'll see `https://greasyfork.org/en/scripts/by-site` which loses the query when clicked.

# Idea
Append the query when clicking **More...** and have the list of sites also retain the query, similar to clicking the site in the main search page sidebar.

**Note**: When searching in the **Filter by site name** field, you would have to use something other than `q` to facilitate keeping the original search parameters.

**Comment by cyfung1031** [comment]
@JasonBarnabe  this is a bug.

**Comment by JasonBarnabe** [comment]
This is not how it's supposed to work. https://greasyfork.org/en/scripts/by-site?q=this+is+a+test is a meaningless search because the "by site" page is searching by the site name, while the main site search is a keyword in the script description.

**Comment by cyfung1031** [comment]
@JasonBarnabe  I rephrase the issue here.

1. Go to the following link - search "test" with domain "google.com"
https://greasyfork.org/en/scripts/by-site/google.com?language=all&q=test&sort=updated
2. In "Showing scripts for:", the user wants to see the results in other domains, but he don't know the exact domain, and he cannot find the required domain in the shown list. he clicked the "show more"
3. redirected to https://greasyfork.org/en/scripts/by-site. This is not what the user wants.
