### ISSUE TITLE
feature request; Add social media buttons on script page

### ISSUE THREAD

**Issue by tiansh** [JasonBarnabe/greasyfork#297]
as what userscripts.org did

**Comment by JasonBarnabe** [comment]
Done with https://github.com/panzi/SocialSharePrivacy

**Comment by tophf** [comment]
There should be an option to not display this block of butt-ons, am I missing something?

**Comment by tobias-engelmann** [comment]
Why should it be there? The buttons you see are only placeholders for the real social media buttons. Therefore you have to click on them to enable the specific social media include. The commit also has no modification to implement such a setting.

**Comment by tophf** [comment]
@tobias-engelmann, the profile setting must exist in order to remove the block of the social butt-ons entirely, obviously. And though I personally can hide it with an adblocker/stylish but my point is that GreasyFork receives more damage from the ugly looking social block than benefiting from an extremely rarely used sharing abilities (0.01% of GF scripts will be shared a few times). I fail to see the reason for unconditionally stuffing this dubious thing for everyone and everywhere, GF isn't a news site.

**Comment by JasonBarnabe** [comment]
I'm not going to be adding prefs to turn site features on or off. If you think it's ugly, I welcome suggestions for improvement. If you don't like the core concept, you know how to get rid of it.

userstyles.org will actually probably get the same kind of buttons soon.

**Comment by tophf** [comment]
Well, it's your site, so if you really don't mind it getting closer to a typical horribly designed site from the 00s, then it'd be only reasonably not to butt in.

**Comment by JasonBarnabe** [comment]
I had tried with the style of buttons userstyles.org has ("line"). The problem is that the same widget coming from the same provider can be different sizes depending on the number of likes/shares/gryzzyls the page has, the language, whether your friends like/share/gryzzyl it too. So you get unused spaces, uneven spacing, no alignment, etc. Also, since the widget is not activated until the user choses, it's impossible to get a good-sized placeholder, so you get things jumping around when the user turns stuff on. With the "box" widgets, the sizes are much more standardized.

If you have a suggestion for how to do this without having tracking on automatically, I'm willing to look into it, but the only I suggestion I've heard so far has been @tobias-engelmann's, and that's the one I used.

**Comment by tophf** [comment]
I see.

And the block should be displayed in its full state with settings and placeholders even for the users who aren't signed in? 

I only ask because it seems like something went wrong, at least I never ever saw a social block with all that placeholders and whistles (see the screenshot) as a plain visitor, moreover typically it's 5-20 times smaller and only has the social buttons per se.

**Comment by JasonBarnabe** [comment]
The settings and placeholders are related to it not tracking you just by loading the page. Typically you are being tracked.

**Comment by tophf** [comment]
Typically those few percent of users concerned about tracking won't be tracked anyway because they use NoScript, Ghostery, ScriptSafe, uBlock, AdBlock and many many others. On the other hand, the majority of visitors will see this absurdly humongous blob for no benefit. Where's the logic? There seems to be none.

**Comment by JasonBarnabe** [comment]
I think at this point, you're just trying to be right rather than trying to be helpful.

If anyone has suggestions on how to improve how this looks or works, please create a new issue with your suggestion. If you don't like the general concept, then you know what to do :)

**Comment by tophf** [comment]
To improve something the first thing to do is to acknowledge its shortcomings. If you, the site owner, would care, then, I guess, you'd either not use this wrecked library or reverted the change after seeing the result and postpone the issue until a better solution is suggested. But you've preferred to shift the discussion from the actual object to mocking the person who cares about the way the site looks. Well then why should I care?

**Comment by tiansh** [comment]
I think the large gray buttons (placeholders) are ugly. Maybe it could be hidden when disabled. Only leave a “share” button / menu there is enough. User can enable any buttons by one click and set it enabled by default. Store the status in user profile or cookies / localStorage. Also maybe some smaller buttons may look better than these ones.

**Comment by JasonBarnabe** [comment]
The placeholders reflect the size of the widgets so that when you activate them, things don't jump around. The sizes of widgets available are limited - see for example https://developers.facebook.com/docs/plugins/like-button. The "button" style does not have a standard width across providers or even in different situations with the same provider, which makes it really hard to lay out a bunch of them. Only the "box" style is more or less standard.

Possible alternatives I can think of:
- Don't use the widget, just use static images/buttons. This way there's no tracking, but you wouldn't get the features the widgets have like showing the number of likes/votes/thumbs up.
- Hide it all under a menu.

**Comment by tobias-engelmann** [comment]
Maybe hide it and display it on a click on the "Share" caption? Then store the display state as a cookie.

So initially it is hidden and with a click on the caption it is possible to show hide it?
