### ISSUE TITLE
Multi-author scripts

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#311]
Allow multiple people to edit a script.

Want to know if people would actually use this before I spend time doing it.

**Comment by tophf** [comment]
Multi-author editing of scripts arguably implies that such scripts are complex, consequently the authors are advanced enough to understand that github would be a much more handy and robust solution for the collaboration.

**Comment by devnoname120** [comment]
@tophf In some cases, this is not enough. Let say for instance that one of the maintainers of a Userscripts goes on vacation (or disappear from the Internet), and that the other needs to modify something in the settings of the script. If he has no way of contacting him, he will be unable to do the needed modifications.

**Comment by tophf** [comment]
@devnoname120, well, are there more than 1 or 2 scripts that would benefit from this? Youtube Center maybe? But it's probably webhooked to Github and everything works automatically, so arguably there's no need to change something. Also, if it's a team then in almost all cases except for disappearance the maintainer can delegate his rights by sharing the password (or making a temporary new one so that his beloved *password123* won't be compromised while he's on vacation). Or the idea is to create a kind of rights management system akin to the forum built-in roles management?

**Comment by JasonBarnabe** [comment]
I intend to do this in a simpified way - an author can add other authors, all of whom will have the same rights. In the future we can add different rights for different users, but I don't see it being worth it right now.

**Comment by tophf** [comment]
Well, on the other hand, I see it might be helpful even for the plain users if the authors are listed as clickable profile links.

**Comment by mapomatic** [comment]
I work with a group of authors writing scripts to help with Waze map editing.  We would LOVE to see this feature added.  Authors constantly come and go, and while we're trying to get more organization with a few of the regular scripters in a GitHub org, it will never be perfect because we can't force anyone to join.  A lot of the authors are new to scripting, aren't comfortable with GitHub, and/or just prefer the quick-and-dirty approach of posting to Greasy Fork.

Sharing a password might work for a small organized group, but we don't have that with Waze scripting.

If we can at least convince authors (as many as possible) to give multiple people access to their Greasy Fork scripts, it greatly reduces the chances that those scripts will be left orphaned, causing future confusion about which fork is the current one. 

Thanks for considering!

**Comment by yooniks** [comment]
te haki nie dzialajom :/ ale nooby je zrobili

**Comment by mapomatic** [comment]
Thank you again for working on this feature!

After adding me (mapomatic) as a 2nd user to this script, the original owner (WazeDev) has lost the ability to update it.  Update, Admin, etc tabs are missing.
https://greasyfork.org/en/scripts/40313-waze-edit-count-monitor

I'm not sure if it's complicating things at all, but I'm listed as the author in the @author script header.

**Comment by JasonBarnabe** [comment]
Known remaining items:

- How does this interact with webhooks?
- How will delete-bans work if the script has multiple authors?
- Provide UI for an author to invite another user and for that user to accept.
- Provide UI to remove authors
- Do we need to allow authors to grant access to a script without granting the ability to add more users?
- Remove shims in code like `script.user`.

**Comment by mapomatic** [comment]
On this script:
https://greasyfork.org/en/scripts/40313-waze-edit-count-monitor
I'm only seeing "Access Denied" on the Update tab.  Also the Admin tab is only displaying the Default Locale and Moderator Log sections.  Another user (added as a multi-user on a couple other scripts) confirmed they're seeing the same thing.

**Comment by dBsooner** [comment]
> On this script:
> https://greasyfork.org/en/scripts/40313-waze-edit-count-monitor
> I'm only seeing "Access Denied" on the Update tab. Also the Admin tab is only displaying the Default Locale and Moderator Log sections. Another user (added as a multi-user on a couple other scripts) confirmed they're seeing the same thing.

I confirm. I am the other user mentioned and I have the same behavior described.

**Comment by JasonBarnabe** [comment]
Should be fixed now.

**Comment by dBsooner** [comment]
Thank you!
