### ISSUE TITLE
Syntax highlighting code editor

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#322]

**Comment by JasonBarnabe** [comment]
Ace editor it is. Done.

**Comment by tophf** [comment]
And for the forum?

**Comment by JasonBarnabe** [comment]
1. #321
2. I'll look in to that.
3. I purposely didn't have it persist because I don't know how it will react to gigantic scripts. Maybe once it's proven that'll change.

**Comment by tophf** [comment]
Regarding the checkbox, just tried it on [YTC](https://greasyfork.org/en/scripts/943-youtube-center/code) and [KOC](https://greasyfork.org/en/scripts/892-koc-power-bot/code), it took ACE 1-2sec in FF and about 1sec in Chrome to complete the highlighting. Faster than the plaintext paste itself which took slightly more than 2sec in FF and about 3sec in Chrome.

Seems like `textarea` wasn't designed to display huge amounts of text, whereas lots of DOM elements in the highlighted container seem to present no troubles for the modern browsers.

I even wonder if it's possible to suppress the textarea initially during pageload and feed the text to ACE directly:
```html
<textarea style="display: block;" id="script_version_code" name="script_version[code]"></textarea>
<script>document.getElementById('script_version_code').style.setProperty('visibility','hidden');</script>
```
plus a call to ACE when its JS is loaded. A separate `<script>` tag instead of a simple `style="visibility:hidden"` is here to esure the text is visible when js is disabled but maybe it's an superfluous precaution because disabling js on a js catalog site is kinda useless.

**Comment by JasonBarnabe** [comment]
How does it react to scripts with lonnggggg lines, like embedded images?

The textarea (or something else) needs to be there so the data is sent on submit. I wonder if you `display: none` the textarea (e.g. with Stylish), does it still take the extra time to load it?

I'm committed to having the site functional without JS enabled. Some people by default don't allow JS. If the syntax highlighting was a user-wide pref, this shouldn't be a problem.

**Comment by tophf** [comment]
Just tried ACE with 650000 char line - no problem.
Hiding the textarea with Stylish doesn't make the page render faster though, apparently.

**Comment by JasonBarnabe** [comment]
Editor is now resizable.
