### ISSUE TITLE
Rework Search

### ISSUE THREAD

**Issue by tobbexiv** [JasonBarnabe/greasyfork#339]
I'd like to see the search on top of the page to be reworked. At the moment you will always search for userscripts. If you want to search for a user, it is not possible. If you want to search for a library, it is not possible. If you want to search for a thread in the forum, you have to use a different search field.

I'd like to be able to search for more things than only userscripts and also have only one search field per page. So if you're on a page the search should search through this page.

Additionally there could be an advanced search where you can specify more specific what you want to search and where (e.g. scripts from user X with keyword Y / scripts and libraries with keyword X). So something similar to the search in Woltlab Burning Boards but for the whole page not only the forum.

**Comment by TimidScript** [comment]
The search mechanism behaves like you are searching in a database using wildcards and what not. It is not for average laymen users who are use to google like type searches. Partial words are also excluded. If you do not know how to use it or you are use to simple google like searches, it hampers rather than helps. 

Example "Baka-Updates" should return Linx-Amender but it doesn't as the first character is adjacent to a parenthesis "(Baka-Updates ...)". "Baka" will not match "(Baka)" or "Baka-Updates". I have not tested it but maybe it is the case for other suffix-postfix character or separators like [@] [|] [/] [-] etc.

Or the Script PixivAuto will never get listed if I type "Pixiv". I need to type "Pixiv*" or PixivAuto to list it.

Another issue is the site search does not behave as one expects. I am not sure if this is intended or not, but basically if I type site:google.com you would expect it to include all scripts that can run on the site, but it makes mistakes in the search and returns an incomplete listing.
Search for "site:google.com" does not return "The Pirate Bay Cleaner" but "site:google" does. In reality "The Pirate Cleaner" on both searches and more. Many scripts should be returned as they are inclusive to all sites. 

I do not think most people know that you can do "site:" search. I found out through a users post. 

IMHO the search functionality by default should be google like, and then have more advance powerful functions.

**Comment by JasonBarnabe** [comment]
The site-wide search has been removed. Each area (users, scripts, forum) has its own search. There is also an advanced search page that lists all the search options and their syntax.

I believe this fulfills the original request.
