### ISSUE TITLE
Use git to get code on webhook request

### ISSUE THREAD

**Issue by jesus2099** [JasonBarnabe/greasyfork#360]
In the same field as #318, I have noticed something strange (but it’s not very serious problem).

I pushed a newer version of [a script](https://greasyfork.org/scripts/2338) (`2015.5.13.1555`) then a few minutes later, before Greasy Fork had updated, I pushed another version ([`2015.5.13.1611`](https://github.com/jesus2099/konami-command/commit/2cd36a81497ed18a7c3da456a36eedb685b7742e)).

When Greasy Fork updated on github web hook, it did take the latest script version (`1611`) code, but its latest commit message was not concatenated in the [script changelog](https://greasyfork.org/scripts/2338/versions) :

> CHG. added another english article (an) to the loose title ignore list

**Comment by JasonBarnabe** [comment]
Greasy Fork will get the commit messages from the webhook, wait a bit for GH's caching to expire, then get the file contents. If you push again before it grabs the file contents, then it's possible for what happened to you to happen.

Really, I think we should update GF to get the library with git rather than over a (caching) HTTP server. That would prevent this problem and makes things better all-around.

**Comment by JasonBarnabe** [comment]
[git archive](http://git-scm.com/docs/git-archive) looks like the best way to accomplish that without pulling the whole repo.

**Comment by JasonBarnabe** [comment]
https://github.com/JasonBarnabe/greasyfork/commit/b602258edd24366dbbc48fcb59d2229a92078f33
