### ISSUE TITLE
Drop assessments

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#386]
Assessments were originally created to let people post their scripts and then have us add their libraries to the whitelist afterwards. I haven't heard anyone ask for additions in a long time, so let's drop the whole concept and make adding a disallowed `@require` a hard validation fail.

**Comment by Ede123** [comment]
I assume this is why https://greasyfork.org/en/scripts/9408-amo-editors is deleted now?

A general comment regarding the removed feature: I didn't even know it existed (and I assume others didn't know either) so the lack of popularity was probably a result of low to none awareness of the feature. (In fact I'm not even sure now where one could have requested such an "assessment"?)

Also another general comment on "Greasy Fork's policy on external scripts": When I initially submitted the script mentioned above I considered to request the required external script to be white-listed. However I was unsure if a) the library would meet the requirements listed on https://greasyfork.org/en/help/external-scripts and b) since there was no dedicated way to request a library to be white-listed (just a general contact link) the whole process seemed like too much of a hassle to me and I just left my where the requirements are less strict  (if there are any at all, I don't know).
What I want to say: Maybe an easier and clearer way to request white-listing of an external library might encourage script authors to do so and therefore make more scripts available from Greasy Fork. If you are open to suggestions in this direction I could open a new issue for this with some ideas.

**Comment by JasonBarnabe** [comment]
When you posted your script it would've told you what was up and you would've had to check a box to acknowledge it. The word "assessment" here was pretty misleading; I don't think this was used in the UI shown to authors.

The whole feature was really for the early days of Greasy Fork. We wanted people to post their scripts, then we could look through the "assessment" list and add things to the whitelist and make it public.

The help doc on the subject I think sums up the reasoning and requirements pretty succinctly, and offers options for what to do if you're hit by this rule. Specific to your situation, things hosted on GitHub will not be added to the whitelist.

If you want to update your script, I can unlock it. I just had to delete all the "pending" scripts as I removed the check that made them not public.
