### ISSUE TITLE
coderay.git is not yet checked out

### ISSUE THREAD

**Issue by maxstarkenburg** [JasonBarnabe/greasyfork#441]
I am trying to follow the instructions for [running GF locally](https://github.com/JasonBarnabe/greasyfork/wiki/Running-Greasy-Fork-locally) (though I can't quite seem to get it to work ... localhost:80 just keeps showing a "Welcome to nginx!" message, and I'm not even sure that's the where I'm supposed to be looking for it, but I digress ...). This time when I tried to get the local instance up and running, at the `rake ts:configure` step, I got the following message:

`https://github.com/JasonBarnabe/coderay.git (at js-ident-unicode@782d189) is not yet checked out. Run ``bundle install`` first.`

Running `bundle install` didn't fix it, and somebody on stackoverflow suggested (to a similar question) running `bundle install --deployment`, which did seem to work. But I'm also guessing it's not the kind of instruction that should be edited into the wiki? (FWIW, this stuff is all pretty new to me, so it could be something I did wrong, but I wanted to report it anyway, just in case.)

**Comment by JasonBarnabe** [comment]
I can't reproduce that problem with a fresh-ish install. It may not be anything specific to coderay; it may be just because it's the first thing listed in Gemfile.lock. `bundle install` should be all you need to install it. It's possible something went wrong the first time you installed.

If you're still having trouble with nginx, you could also try running `rails server` then going to http://localhost:3000. You won't be able to run the forum that way, though.

**Comment by maxstarkenburg** [comment]
Thanks, Jason. I'll go ahead and close the issue then. Thanks for the tip on running `rails server`. That did the trick for my needs.
