### ISSUE TITLE
RTL design

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#460]
Update the design of the site to be friendlier to people in RTL locales.

**Comment by IndianaJaws** [comment]
Please do that, just start by making the paragraphs RTL, it will help immensely. Kinda bums out to be on the transifex team and your translation is kinda lost cause of RTL-LTR problems.

**Comment by JasonBarnabe** [comment]
@IndianaJaws Any suggestions welcome; I don't know what I'm doing with this, I just know something needs to be done.

**Comment by IndianaJaws** [comment]
even the simplest tag does so much (it handles pretty well the rtl-ltr languages integration)
![image](https://user-images.githubusercontent.com/53814901/62819679-f5680400-bb60-11e9-8d5b-fe20fbd7f92f.png)
to >
![image](https://user-images.githubusercontent.com/53814901/62819682-0284f300-bb61-11e9-95e2-bcdd9d804846.png)
Is perfect.
I'm just not sure (and currently don't have the time) to dive into the code of how the translations are generated, and so where would one push the "style" or "dir" tag into the html. 
because if you put dir="rtl" over everything it messes up with the logo on the top navbar,
but if we can just push it into every paragraph's text i think it should do amazing

**Comment by JixunMoe** [comment]
so apply this style to `h1`~`h6`, `p` tag should handle most of the case I guess...?

**Comment by IndianaJaws** [comment]
I think so, yeah

**Comment by JasonBarnabe** [comment]
I've applied `direction: rtl` to some choice sections. Let me know if there's something specific I missed.

I'm wondering what should happen when you choose an RTL language but are viewing a style that has LTR content only. Should that be `direction: rtl`-ed too?

**Comment by IndianaJaws** [comment]
Most of it looks great :)
You missed:

- forum page: Everything in it
- users: everything but the sidebar, 
- libraries: only title and its explanation
- moderator_actions: title of table, although because the reasons and actions are always in English, I think we should somehow swap it back? like only the content of reason and action
- users/sign_up, users/sign_in, users/password/new  - the form-boxes titles should be on the right as well 

What type of LTR content do you mean? If you mean the photos in the homepage for example, it probably should but I'm not sure how much of a hassle it is

**Comment by JasonBarnabe** [comment]
I've made a change and applied it to everything except the header and forum. I also adjusted a couple places where left/right where explicitly set for layout purposes. Let me know if anything else looks weird.

By LTR content I mean like if you go to https://greasyfork.org/he/scripts/7687-moremovieratings. The name and description are in English. The titles probably are fine with being right-aligned like that, but the pink area at the bottom looks odd. I think that should inherit the directionality of the language it was written in?

**Comment by IndianaJaws** [comment]
Yeah, it does kinda look weird like that. inheriting the directionality is better. can it be applied to stuff like the photos in the homepage (i.e they will swap sides for RTL languages?)

It looks pretty dope right now! I'm also almost done with translating in transifex.
there are some stuff that look  weird, but i think it's meaningless mostly,  like:
![image](https://user-images.githubusercontent.com/53814901/62955423-b3a5ba80-bdf9-11e9-8b30-5a338c810a96.png)
(overlay of text and image, in a couple of places)

**Comment by JasonBarnabe** [comment]
Fixed the search field, homepage images, and the LTR additional info.

There's still some wacky stuff going on when in RTL mode viewing LTR names with punctuation, for example [this](https://greasyfork.org/he/scripts/380664-%E6%96%B0%E5%A2%9E%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD%E9%80%9A%E9%81%93-%E7%99%BE%E5%BA%A6%E4%BA%91%E6%8F%90%E5%8F%96%E7%A0%81%E7%A0%B4%E8%A7%A3-%E8%87%AA%E5%8A%A8%E6%8F%90%E4%BA%A4%E4%BB%A5%E5%8F%8A%E7%99%BE%E5%BA%A6%E4%BA%91%E9%99%90%E9%80%9F%E7%A0%B4%E8%A7%A3-%E9%99%84%E8%B5%A0%E7%99%BE%E5%BA%A6%E4%BA%91%E4%BC%9A%E5%91%98?locale_override=1). The punctuated part gets moved to the right for some reason?

Also the list of styles on the homepage are missing links (because that's the side it decides to truncate).

**Comment by JasonBarnabe** [comment]
Fixed the punctuation issue. If there are further improvements to be made, new issues can be filed.
