### ISSUE TITLE
Promote Tampermonkey for everything

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#466]
Tampermonkey apparently now supports a lot of browsers. We should mention them on https://greasyfork.org/en/help/installing-user-scripts

@derjanb what browsers do you have good enough support for that you would like them to be promoted, and what are the proper install URLs?

**Comment by derjanb** [comment]
Hi Jason, thanks for mention Tampermonkey at this help page. :)

Besides the [Chrome](https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo) version there are versions for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/), [Safari](http://tampermonkey.net/?browser=safari), [MS Edge](https://www.microsoft.com/store/apps/9NBLGGH5162S) and [Opera 15+](https://addons.opera.com/en/extensions/details/tampermonkey-beta/).
All versions are working in general, but each platform has some specific limitations. Especially the Firefox and the MS Edge version do have some limitations, because their (web) extension support is work in progress, but most scripts will work, though. So from my point of view all of the above can be promoted.

There are also some Android versions, but their functioning depends on the Android version, the CPU architecture and so on. 
So for Android my recommendation is to try [Yandex Browser Beta](https://play.google.com/store/apps/details?id=com.yandex.browser.beta) and Tampermonkey because this browser is based on Chromium and has native extension support enabled.

**Comment by JasonBarnabe** [comment]
Suggested list has been updated.
