### ISSUE TITLE
Highlighted scripts: anonymous user sees always the same locale scripts

### ISSUE THREAD

**Issue by tobbexiv** [JasonBarnabe/greasyfork#486]
If I log in to my account I see scripts in the locale I select in the dropdown (e.g. German, Italian, ...). If I visit the site as an anonymous user I see always scripts in the same locale (presumingly chinese). This is independent from the locale I choose in the dropdown.

**Comment by JasonBarnabe** [comment]
Scripts are eligible for being in the highlighted script list based on a few criteria, for example for anonymous users, they can't have adult content. It will then get scripts that match the current locale, and sample 5 from the top 20% based on install count. If there are less than 5 in the top 20%, then it will use more from the top 20% from any locale.

The problem is that some locales have few scripts. I just tested with German, and it has 4 eligible scripts for an anonymous user. 20% of 4 is... 0. So the rest are from whatever locale, and Chinese is actually the most popular locale on the site.

I have modified it so that if the top 20% of the locale is less than 5, then it will sample from all scripts in that locale. Only if that's still not enough will it move on to other locales.

**Comment by tobbexiv** [comment]
Ok, I got it. But how is the locale determined? Is it only what I have as descriptions for the script or refers it to all scripts with a localized description / name in this locale?

**Comment by JasonBarnabe** [comment]
Either the script is set to that locale (via the locale drop down when you post it), or has a localized name/description in that locale.

**Comment by tobbexiv** [comment]
Then there seems to be something broken. I just did a quick google search and found way more than 4 scripts with `@name:de`: https://www.google.de/#q=site:greasyfork.org+%22%40name:de%22

**Comment by JasonBarnabe** [comment]
There is a whitelist of scripts that are allowed to show Adsense ads, and since the home page includes an Adsense ad for anonymous users, only those scripts will be listed. I periodically manually review the most popular non-whitelisted scripts to add to the whitelist.
