### ISSUE TITLE
Some scripts specify names and descriptions multiple times

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#492]
Some scripts seem to have multiple names and descriptions for a locale. Looks to be they set a default name and a default locale, but also specified a localized name for that locale. Prevent or handle better.

https://greasyfork.org/en/scripts/28276-解除网页右键限制

**Comment by strongop** [comment]
I think it's a good idea to support multi line description, because I want to update my script in one place,
like github.
I may add some more features to the script and update the description, and the webhook will update the script to greasyfork.
Currently I need to goto greasyfork to manually update the descriptions,
otherwise the info page will be out of dated.

**Comment by strongop** [comment]
And github will keep all the description history

**Comment by JasonBarnabe** [comment]
@ghost Multiline descriptions would need to be supported by user script managers. I don't see the need anyway.

Greasy Fork already has a GitHub webhook feature.

**Comment by JasonBarnabe** [comment]
Supplying a localized name or key in the script's default locale is now a validation failure.
