### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by TomRobert** [JasonBarnabe/greasyfork#493]
The certificate expired for greasyfork.org. Can you renew it?

**Comment by JasonBarnabe** [comment]
Put in the request. Thanks for letting me know. I still think it's weird they don't send reminders...

**Comment by CollinChaffin** [comment]
You beat me to it, LOL.  If they aren't sending you the normal multiple expiration reminders then I would contact their support perhaps they just have an old outdated address on file etc.

**Comment by cvzi** [comment]
Is there an easy way to access the site?

**Comment by jesus2099** [comment]
The installation of scripts from anywhere that includes libraries from Greasy Fork fails.

**Comment by Alain1978** [comment]
Hello, I confirm since last night, your security certificate has been expired. I use Firefox so it's impossible to access to the website.
![canvas1](https://cloud.githubusercontent.com/assets/18900339/25307847/efdfa2fc-27a8-11e7-9b17-6a56ceab247b.png)

**Comment by CollinChaffin** [comment]
Okay let me first preface this using proper markdown for the disclaimer: :)


# DANGER WILL ROBINSON!! 
## I TAKE NO RESPONSIBILITY FOR ANY OUTCOME IF YOU CHOSE TO ENABLE THIS OPTION
### Do not run in any production environment with this configuration option enabled and revert/disable this option once GF cert is renewed!!
----
#### Yes, I want to continue because I cannot live without GreasyFork another moment!
----

<br>
<br>
<br>

` "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --ignore-certificate-errors `

<br>
<br>
<br>

**Comment by Royalgamer06** [comment]
Or ![](https://i.imgur.com/I6q2qsj.png)

**Comment by CollinChaffin** [comment]
Right but you cannot click that in any recent version of Chrome without running with that flag - you get this screen instead because of HSTS:

![snag_4-22-2017_18-22-20](https://cloud.githubusercontent.com/assets/9301483/25309081/c0253b6e-2788-11e7-92d4-8dfc56960160.png)

**Comment by CollinChaffin** [comment]
@Royalgamer06 you may want to dump/print your running chrome flags my guess/bet is.....you're already running with that unsafe switch enabled you set at some past point if you got a screen allowing you to click proceed when there is HSTS involved.

**Comment by JasonBarnabe** [comment]
OK, we're back now. There seems to be some issue with them emailing me as not only did I not receive reminders, I did not receive the certificate until someone manually intervened.

Thanks for giving me a heads up. Maybe someone will remind me in April 2020.
