### ISSUE TITLE
RawGit CDN links with release tags are not whitelisted

### ISSUE THREAD

**Issue by chocolateboy** [JasonBarnabe/greasyfork#494]
The [recently-added support](https://github.com/JasonBarnabe/greasyfork/issues/476) for RawGit URLs is excellent, but it doesn't extend to [release tags](https://github.com/chocolateboy/userscripts/commit/656a50ca01f9beb6bbbe143d9f14795b085d301d) or [shortened commit-hashes](https://github.com/chocolateboy/userscripts/commit/0a2ca5facd7279a0d3030cfb1206dc05a802d6dd):

> Script sync failed - Code uses an unapproved external script: `@require` https://cdn.rawgit.com/urin/jquery.balloon.js/1.1.2/jquery.balloon.js.

Short hashes are more readable than the full hash, and, unlike hashes, tags convey something to the developer as well as anyone auditing the code e.g.:

> https:\/\/cdn.rawgit.com/urin/jquery.balloon.js/**1.1.2**/jquery.balloon.js

is more instructive than:

> https:\/\/cdn.rawgit.com/urin/jquery.balloon.js/**8b79aab63b9ae34770bfa81c9bfe30019d9a13b0**/jquery.balloon.js

RawGit's production URLs (i.e. `https://cdn.rawgit.com/user/repo/tag/file`) are guaranteed to be immutable, regardless of what comes after the repo name, so adding further restrictions to the URL is redundant.

**Comment by JasonBarnabe** [comment]
> RawGit's production URLs (i.e. `https://cdn.rawgit.com/user/repo/tag/file`) are guaranteed to be immutable

If this is true, then it's OK with me. Can you point to some documentation that states this? What happens if you tag something, delete the tag, and reuse the tag later?

**Comment by chocolateboy** [comment]
cc @rgrove

Thanks for considering this. I'm basing this on the description on the [front page](http://rawgit.com/) ("Files are cached **permanently** based on the URL"), which is elaborated in the [FAQ](https://github.com/rgrove/rawgit/blob/master/FAQ.md) e.g.:

> #### What's the difference between development and CDN URLs?
>  Requests to cdn.rawgit.com (a CDN URL) are ... cached **permanently** at the CDN layer based on the URL ... reloading won't fetch new changes from GitHub.

And:

> #### How long does the CDN cache files? How can I make it refresh my file?
> The CDN caches files **permanently** based on their path. ... To ensure that the CDN always serves the version of the file you want, **use a git tag or commit hash** in the file's path instead of a branch name, and update the URL if you push a new version of the file.

**Comment by rgrove** [comment]
Hi, I run RawGit and have apparently been summoned!

> If this is true, then it's OK with me. Can you point to some documentation that states this? What happens if you tag something, delete the tag, and reuse the tag later?

It's true that the RawGit CDN treats tag and commit-based URLs as immutable. RawGit even serves them with the `Cache-Control` `immutable` directive and a far-future `max-age`, instructing both browsers and CDN nodes to cache them essentially permanently. There are some caveats though:

-   The CDN consists of many geographically distributed nodes. Each node maintains its own cache and will evict the least-recently used URLs as necessary in order to make space in the cache for more recently requested URLs. If a URL is popular, then it could remain in the cache indefinitely, but it is possible for an unpopular URL to fall out of the cache, or to be cached on one node but not another.

-   As you point out, it's possible for someone to push a tag to git, delete that tag, and then reuse it for a different commit. This would be analogous to replacing the contents of a file without renaming it on a traditional CDN origin, and could result in one or more cache nodes having stale content or content that differs from another cache node. In my years running RawGit, though, I don't think I've ever actually seen this scenario.

-   Very rarely, a situation arises that requires me to purge all cached content. This means the CDN will need to revisit GitHub the next time a URL is requested, which means there's a chance the new content could differ from the previously cached content if someone has deleted and reused a tag, or content may no longer be available if a repository has been deleted.

So, while the RawGit CDN treats tag and commit URLs as immutable and tries to cache them for as long as is practical, the word "permanent" is technically used in a best-effort sense. From the previous comments in this issue it sounds to me like that's probably fine for your use case, but I'll let you be the judge.

Hope this helps.

**Comment by chocolateboy** [comment]
@rgrove thanks for pointing out the caveats.

It looks like the full hash is the best protection against these (admittedly rare) exceptions. An adversary would need a lot of luck but only a modicum of determination to exploit one of these vectors to inject a malicious script, but generating a hash collision still remains unfeasible, [I think](https://github.com/blog/2338-sha-1-collision-detection-on-github-com) (IANAC), so I'll stick with the full hash.

Thank you both for these two great services that taste great together!
