### ISSUE TITLE
External script should be verified by it's checksum not it's URL

### ISSUE THREAD

**Issue by ghost** [JasonBarnabe/greasyfork#583]

**Comment by JasonBarnabe** [comment]
Can you elaborate on how you think this would work?

**Comment by strongop** [comment]
Some way Similar to:
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
https://www.w3.org/TR/SRI/

But may need support by user script managers, i.e. Greasemonkey/Tampermonkey/..., since the @required script might be modified later. (here I assume user script managers may update the sub script, or Users install a user script from a local file.)
By append the checksum to the `@require` directive.

Think there are several steps during which the integrity of the `@required` sub scripts should be checked.
1. The script author create/update a script.
2. A user install/update the script
2.1 greasyfork should check the integrity before enable the install/update button
2.2 --or-- check that before send the script content to the user script manager, send a dummy one if check failed.
2.3 user script manager should check the integrity before install/update the script.

@arantius @Sxderp @derjanb

**Comment by derjanb** [comment]
SRI is already supported by Tampermonkey. MD5 does always work, others depend on window.crypto. At the next beta version MD5 and SHA256 will always work.

https://tampermonkey.net/documentation.php?ext=dhdg#Subresource_Integrity

**Comment by strongop** [comment]
Tampermonkey already support integrity check.
https://tampermonkey.net/documentation.php?ext=dhdg#_require

**Comment by Sxderp** [comment]
@derjanb From the documentation it looks like the script will continue to install even if the check fails, just without the particular resource / requires. Correct?

**Comment by derjanb** [comment]
@Sxderp Yes, that is correct. Resources are empty then and invalid requires simply log a warning to the console when the script is executed.

**Comment by JasonBarnabe** [comment]
Greasy Fork only specifies a list of trusted domains - it's assumes anything on that domain is OK to use. This is a protection against script authors hiding malware in their requires.

Resource integrity is best handled by the script managers as they can validate the same request that is cached for use. The way this is defined in https://tampermonkey.net/documentation.php?ext=dhdg#_require should be compatible with what Greasy Fork is doing.
