### ISSUE TITLE
[Suggestion] Add something similar to issue template to greasyfork

### ISSUE THREAD

**Issue by maple3142** [JasonBarnabe/greasyfork#597]
As mentioned in title, I think it is good to have something similar to issue template in GitHub. I found that many users tend to submit feedback without providing some important information, so it would be great to have a ability to tell them to provide them.

**Comment by JasonBarnabe** [comment]
I'd be fine with updating the text presented to users when they post a review/question. I don't want to provide a way for authors to do this because I think a lot of them would abuse it. If people really want customizable issue templates, they can provide a `@supportURL` pointing somewhere that supports it.
