### ISSUE TITLE
[Feature Request] Implement obsolete tag

### ISSUE THREAD

**Issue by Cyberavater** [JasonBarnabe/greasyfork#620]
There are many scripts on Greasy Fork which are no longer maintained. Thus has zero use but because it was popular at a time it keeps coming up at the top and people without knowing it installs it and it keeps being at the top.

Greasy Fork can be used for archiving old unusable scripts but obsolete tag should separate them.

**Comment by JasonBarnabe** [comment]
Who would set the tag? If it's the author, why not just delete/unlist?

**Comment by Cyberavater** [comment]
No, not the author. Most of the time the author forgets about the script. Rather it should be tagged after a resonable amount of reports from the trusted users.

**Comment by JasonBarnabe** [comment]
There's currently no concept of "trusted users", and there's currently nothing in the rules about scripts that stop working. This may change, but that's the current state.

**Comment by Cyberavater** [comment]
I see... Well, we can have it voted by the regular registered user & set a limit bypassing which will give the script an 'Obsolete' tag, which will be removed if the version updates. How about it?

**Comment by eight04** [comment]
Does down-voting drops its priority?

**Comment by JasonBarnabe** [comment]
Current behaviour for script reports is that if a user has created at least 3 reports in the past and has had a moderator uphold those reports at least 75% of the time, any new report they create will make the script hidden until it's reviewed by a moderator. Note that this is only for rule violations, not general "this script doesn't work" stuff.

New behaviour coming up: if the last three reviews rated the script "bad", and all occurred since the last script update, and the author did not comment on any of those reviews, the site will send an email to the author saying that they should reply to the reviews or update their script within two weeks, otherwise it will be soft-deleted.

I think this new behaviour strikes a good balance between the author and the users. The script doesn't get hidden if the author responds in some way.

**Comment by Cyberavater** [comment]
Ya, that'll be really nice, but the occurring of the issue should not be limited to after a few days of update, as to consider a case where the script worked fine after the update for site 'X' but after a month it got obsolete because site 'X' updated their site. So, there should be a rule for that as well (For such cases the/after a period of time, the limit could be increased to 5 if not 3).

**Comment by JasonBarnabe** [comment]
It will not limited to recently after an update. It's just that the update will "reset" the counter, so if you (as a script author) get 3 bad reviews and then update the script, your script will not be deleted.

If you don't update the script (or respond to the reviews) within 2 weeks, then the script will be deleted.

**Comment by JasonBarnabe** [comment]
This has been launched. There are currently 56 scripts that meet the criteria.
