### ISSUE TITLE
Add a checkbox to discussions (and maybe comments) to enable notifications

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#707]

**Comment by darkred** [comment]
I'd like to make a suggestion regarding this feature:

when the user has set the notifications as ` Get an email when discussions are posted on your scripts or when those discussions get new comments` ([screenshot](https://user-images.githubusercontent.com/723651/89061691-d49a4f00-d36d-11ea-879b-925444a5e8bb.jpg))
then, when going to replying to such a discussion on a script of yours that has got new comments,
the `Notify me of any replies` checkbox to be ticked (because it's effectively enabled) :
![2020-07-31_203915](https://user-images.githubusercontent.com/723651/89061961-4e323d00-d36e-11ea-949b-7b08f59bcc47.jpg)
