### ISSUE TITLE
Analytics page for script authors

### ISSUE THREAD

**Issue by knoajp** [JasonBarnabe/greasyfork#774]
I want to know some analytic data on each of my scripts other than installs and update checks on existing stat page, such as...

- user language (on greasyfork or navigator.language)
- referer (where did they come from?)
- search keywords (on greasyfork or from google, etc.)
- access count 

if greasyfork (will) just storage such data, I can try to write some view.

Or permitting authors to add Google Analytics code(or registering just an ID of it) or something to script pages is also helpful.

**Comment by JasonBarnabe** [comment]
There's a lot of privacy stuff that goes along with this.

I'd be open to allowing adding an analytics library or something, but not sure how that works when the owner of the site is not the same as the one who has access to the analytics account.

**Comment by knoajp** [comment]
I see.
Maybe if you permit only Google Analytics or something famous and trusted services, I think no security issues would happen.
And like blog services, the site owner could allow users to adding differnt account analytics tag.

**Comment by knoajp** [comment]
I see.
Maybe if you permit only Google Analytics or something famous and trusted services, I think no security issues would happen.
And like blog services, the site owner could allow users to adding differnt account analytics tag.

**Comment by JasonBarnabe** [comment]
I'm not comfortable with this.

- How do I know that Greasy Fork won't be blamed for violations of TOS of the analytics software?
- How do I know that other data from Greasy Fork won't get leaked to the analytics software?
- This would require updating the privacy policy, and it would be awkward because I wouldn't be able to list where the data goes.

With blog services, each blog is considered a separate site. That's not the case with Greasy Fork.
