### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by zacny** [JasonBarnabe/greasyfork#849]
When I try to open same feedback pages, I get an error 500 from serwer.
(Few samples from top scripts of page: https://greasyfork.org/pl/scripts)
https://greasyfork.org/pl/scripts/34613-youtube-multi-downloader-v6-2-mp3shack-com-mp3-mp4-hd-no-ads/feedback
https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod/feedback
https://greasyfork.org/pl/scripts/376246-youtube-mp3-downloader-v2-1-mp3offline-org-no-ads/feedback
https://greasyfork.org/pl/scripts/391872-adguard-popup-blocker/feedback

**Comment by JasonBarnabe** [comment]
This is due to [a bug in a library Greasy Fork uses](https://github.com/iGEL/it/issues/30). The bug occurs when tou are viewing in a language other than English that:

1. Does not have a translation for a specific string used on that page.
2. Has more plural forms than English.
3. The number of people favouriting the script is such that it triggers a plural form that English doesn't have.

I'm hoping to get the library fixed, but until then, if you translate [this string](https://www.transifex.com/greasy-fork/search/?q=source_text%3Afavorited+target_language%3Apl) (you may need to visit that specific link again if you have to register or log in to Transifex), then the problem will go away for Polish.

**Comment by zacny** [comment]
Thank you for an quick answer. I tried to use this link on transifex, but seems to be broken.

**Comment by JasonBarnabe** [comment]
Dunno, link works for me. If you've made a Transifex account then search for source_text:favorited.

![image](https://user-images.githubusercontent.com/583995/103467458-e2853f00-4d14-11eb-8b98-d13258d2c4df.png)

**Comment by zacny** [comment]
Should be done now.

**Comment by JasonBarnabe** [comment]
Thanks, I've deployed the translations. The page should not give an error any more (at least in Polish).

**Comment by zacny** [comment]
Thank you too.
