### ISSUE TITLE
`Diff selected versions` links sometimes don't work ("404 - page not found") if the current page is of an intermediate version

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#859]
For example for this script https://greasyfork.org/en/scripts/6779-markdown-toolbar-for-uso
Its latest version is 1.4.9.1.

If you are in e.g. this intermediate version 1.4.7
https://greasyfork.org/en/scripts/6779-markdown-toolbar-for-gf-and-uso?version=179573
and switch to the `History` tab
and click the preselected `Diff selected versions` button to diff between v1.4.9.1 and v1.4.9
you'll get in this invalid page: https://greasyfork.org/en/scripts/6779-markdown-toolbar-for-uso/diff
showing: "404 - page not found" :
![2021-01-10_194242](https://user-images.githubusercontent.com/723651/104130913-0fbc9780-537c-11eb-96f0-5a6e10e71339.jpg)
The same happens with any other version pairs I choose to diff.

---

It occurs with almost all intermediate version pages, with just one exception: 1.4.8
https://greasyfork.org/en/scripts/6779-markdown-toolbar-for-gf-and-uso?version=845308
With that version the diff links work all ok.

In that specific version 1.4.8 I was added as a co-author by wOxxOm.
(maybe this has to do with this?)

**Comment by JasonBarnabe** [comment]
The problem was with the code that redirects when the slug (`markdown-toolbar-for-gf-and-uso`) is not the proper value. The script got renamed at some point, so there's a different slug if you look at older versions. When you do the diff, it redirected back to the updated slug, but didn't retain the parameters of what you were trying to diff.

It's fixed now.

**Comment by darkred** [comment]
Thank you.
