### ISSUE TITLE
Can't sign in with GitHub

### ISSUE THREAD

**Issue by JRice15** [JasonBarnabe/greasyfork#870]
I tried to sign in with GitHub after creating my account via that method a few days ago. Now, when I click the "Sign in with GitHub button" it simply redirects me back to the signin page, and does not sign me in. 

Browser: Safari 14.0
OS: OSX Catalina, 10.15.7

**Comment by JasonBarnabe** [comment]
I just tried with my account, worked fine.

Can you provide a network log of some sort? Just need to know the URLs visited/redirected to.

**Comment by JRice15** [comment]
Seems to go here which redirects back to signin: https://github.com/login/oauth/authorize?client_id=f48f3632e1d4f0f26e7d&redirect_uri=http%3A%2F%2Fgreasyfork.org%2Fauth%2Fgithub%2Fcallback&response_type=code&scope=read%3Auser%2Cuser%3Aemail&state=a26ef6de32b762f8853c3bae1683fd4bc8584db358cf4ed8

**Comment by JasonBarnabe** [comment]
I made a change just now - can you try again?

**Comment by JRice15** [comment]
Yep, that worked. Thanks for the quick responses!

**Comment by JasonBarnabe** [comment]
Just FYI, I'm setting up another server behind a load balancer, and this server didn't understand that it was accessed via https, so the redirect_uri said http instead of https, which caused a mismatch with what GitHub is set up to expect. Not all traffic gets to this new server, so that why I didn't see it.

Thanks for reporting!
