### ISSUE TITLE
Consider removing the 5 min limit for editing your own comments

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#976]
Starting from this commit https://github.com/JasonBarnabe/greasyfork/commit/e2accb96cd9598e6abfefb6e0593e19bd64f3951, editing your own comments is available for only 5 minutes after creation.

In the old comment/review method for scripts, one could edit their own posts anytime. 
I'd like to ask you please to consider restoring that behavior.

The current 5-min limit is very short, but I don't want to ask to make it, e.g. 10 min.
What I have in mind is GitHub, where one can edit (and delete) any of their own comments in issues/PRs/discussions anytime.

Plus, it would facilitate those who want to directly update their rating on a script, without having to make an accompanying comment.

**Comment by JasonBarnabe** [comment]
The reasons for this are:

- Editing your comment can make subsequent comments not make sense.
- It makes you think about what you're going to post, instead of just posting whatever and then editing.
- It makes it harder to hide abuse or other things.

The editing window is meant just for typos you notice after posting.

If you want to change a rating, you can post a new comment with an updated rating. Just post a simple "Thanks it's fixed" or whatever makes sense in context.

**Comment by darkred** [comment]
> If you want to change a rating, you can post a new comment with an updated rating. Just post a simple "Thanks it's fixed" or whatever makes sense in context.

Just to clarify, I have in mind those users that give bad/ok rating to scripts, and then wrongly suppose they can't change it afterwards, and so they just leave it as is, not caring to ever update it. 
Would it be helpful to display that info as a heads-up right below the "Post comment" button ? Here is a mockup:
![2021-08-20_182707](https://user-images.githubusercontent.com/723651/130256721-adcef8a4-df99-4588-8846-1fa0f1420cd1.jpg)

**Comment by JasonBarnabe** [comment]
Sure, I've added a note like that.
